@url = http://localhost:5000/api

GET {{url}}/client/e0c4b8f7-368e-47c8-8fec-1fe094e6d118
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiN2M5NjA1NjktMDBiZi00ZDYyLWI3MjYtYTVhMjY3MTM0ODU5Iiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY0NTEzNzcwOSwiZXhwIjoxNjQ1MTM4MDA5fQ.AbuZryhHMk8mhw0Sb3Sq6a_IwmIPlw3BSIxDpROBeOQ


### GET ALL CLIENTS (NEEDS AUTH)
GET {{url}}/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNzRhNWY5MjUtMWQyYi00OWYyLTg3Y2EtZDA3YzMxYTIxN2JlIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY0NTQ4MjIzMCwiZXhwIjoxNjQ1NDgyNTMwfQ.nJQ7WMDmqypBVSR5xEWrmBDere0-2pgAXquqFTwCDYY


### REGISTER CLIENTS
POST {{url}}/clients
Content-Type: application/json

{
  "firstname": "Luis",
  "lastname": "Diaz",
  "email": "luis@diaz.com",
  "role": "client",
  "password": "liverpool",
  "cardNumber": 55254507111,
  "balance": 1000,
  "hobbies": ["football", "dancing", "golf"]
}


### LOGIN
POST {{url}}/auth/login?user_type=client
Content-Type: application/json

{
  "email": "sadio@mane.com",
  "password": "liverpool"
}


### REFRESH TOKEN
GET {{url}}/auth/refresh-token


### LOGOUT
GET {{url}}/auth/logout?user_type=client


###
PUT {{url}}/clients/6743e0bc-932f-43d2-b143-d5fb9e8b8ebd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNjc0M2UwYmMtOTMyZi00M2QyLWIxNDMtZDVmYjllOGI4ZWJkIiwibGFzdG5hbWUiOiJNYW5lIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NDQ5NjI4MzkuMzA0LCJpYXQiOjE2NDQzNTgwMzl9.vJTFDXKbGbTCeYKCrU0XLS98HLdgautPl9Gp26K68tw

{
  "balance": 1000,
  "role": "client"
}


###
DELETE {{url}}/clients/e543a8fe-3f39-443e-8e94-745d88d456e8


### CREATE TRANSACTION
POST {{url}}/clients/e543a8fe-3f39-443e-8e94-745d88d456e8/transactions
Content-Type: application/json

{
  "amount": 2500,
  "type": "deposit",
  
}

################################
## BANKER
################################

### REGISTER BANKERS
POST {{url}}/bankers
Content-Type: application/json

{
  "firstname": "Jamie",
  "lastname": "Carragher",
  "email": "jamie@carragher.com",
  "role": "banker",
  "password": "liverpool",
  "employeeNumber": 2564589710
}

### 
GET {{url}}/bankers


### LOGIN BANKER
POST {{url}}/auth/login?user_type=banker
Content-Type: application/json

{
  "email": "xabi@alonso.com",
  "password": "liverpool"
}
